/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admin_View;

import Model.Community;
import Model.DoctorDirectory;
import Model.PatientDirectory;
import Model.Person;
import doctor_view.Doctor1Screen;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import patient_View.patientFrame1;

/**
 *
 * @author JINESH
 */

public class adminFrame extends javax.swing.JPanel {

    /**
     * Creates new form adminFrame
     */
        JPanel bottomPanel; 
    Person persons;
    PatientDirectory patients;
    DoctorDirectory doctors;
    private Community selectedPerson;
    public adminFrame() {
        initComponents();
        doctors=new DoctorDirectory();
        persons=new Person();
        patients=new PatientDirectory();
    }

    public adminFrame(JPanel bottomPanel, Person persons) {
        
    this();
     this.bottomPanel=bottomPanel;
        this.persons=persons;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        districtField = new javax.swing.JTextField();
        cityField = new javax.swing.JTextField();
        provinceField = new javax.swing.JTextField();
        pincodeField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        viewCommunityDetailsLabel = new javax.swing.JLabel();
        searchLabel = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        viewButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        locationLabel1 = new javax.swing.JLabel();
        districtLabel1 = new javax.swing.JLabel();
        cityLabel1 = new javax.swing.JLabel();
        provinceLabel1 = new javax.swing.JLabel();
        adminViewLabel = new javax.swing.JLabel();
        addCommunityDetailsLabel = new javax.swing.JLabel();
        pincodeLabel1 = new javax.swing.JLabel();
        locationField1 = new javax.swing.JTextField();
        locationLabel = new javax.swing.JLabel();
        districtField1 = new javax.swing.JTextField();
        districtLabel = new javax.swing.JLabel();
        cityField1 = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        provinceField1 = new javax.swing.JTextField();
        provinceLabel = new javax.swing.JLabel();
        pincodeField1 = new javax.swing.JTextField();
        pincodeLabel = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        locationField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        patient1Button = new javax.swing.JButton();
        doctor1Button = new javax.swing.JButton();
        communityButton = new javax.swing.JButton();

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        viewCommunityDetailsLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        viewCommunityDetailsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewCommunityDetailsLabel.setText("View Community Details");

        searchLabel.setText("Search");

        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        locationLabel1.setText("Location ");

        districtLabel1.setText("District");

        cityLabel1.setText("City");

        provinceLabel1.setText("Province");

        adminViewLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        adminViewLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminViewLabel.setText("Admin View");
        adminViewLabel.setToolTipText("");

        addCommunityDetailsLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addCommunityDetailsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addCommunityDetailsLabel.setText("Add Community Details");

        pincodeLabel1.setText("Pincode");

        locationField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationField1ActionPerformed(evt);
            }
        });

        locationLabel.setText("Location ");

        districtLabel.setText("District");

        cityLabel.setText("City");

        provinceLabel.setText("Province");

        pincodeLabel.setText("Pincode");

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        locationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationFieldActionPerformed(evt);
            }
        });

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Location", "District", "City", "Province", "Pincode"
            }
        ));
        jScrollPane1.setViewportView(userTable);

        patient1Button.setText("Patient");
        patient1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patient1ButtonActionPerformed(evt);
            }
        });

        doctor1Button.setText("Doctor");
        doctor1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctor1ButtonActionPerformed(evt);
            }
        });

        communityButton.setText("Community");
        communityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(adminViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(addCommunityDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(viewCommunityDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pincodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(locationLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cityLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(districtLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(provinceLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(76, 76, 76)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(provinceField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cityField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(districtField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(locationField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pincodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addComponent(saveButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(patient1Button)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(doctor1Button)
                                        .addGap(18, 18, 18)
                                        .addComponent(communityButton)))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(pincodeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(locationLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cityLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(districtLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(provinceLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(76, 76, 76)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(provinceField1, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cityField1, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(districtField1, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(locationField1, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(pincodeField1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(86, 86, 86)
                                                .addComponent(updateButton)))
                                        .addGap(163, 163, 163))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(viewButton)
                                            .addGap(18, 18, 18)
                                            .addComponent(deleteButton)
                                            .addGap(12, 12, 12))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(97, 97, 97)
                                            .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(75, 75, 75)
                                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patient1Button)
                    .addComponent(doctor1Button)
                    .addComponent(communityButton))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewCommunityDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteButton)
                            .addComponent(viewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(locationLabel1)
                            .addComponent(locationField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(districtLabel1)
                            .addComponent(districtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityLabel1))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(provinceLabel1)
                            .addComponent(provinceField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pincodeLabel1)
                            .addComponent(pincodeField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addCommunityDetailsLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(locationLabel)
                            .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(districtLabel)
                            .addComponent(districtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityLabel))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(provinceLabel)
                            .addComponent(provinceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pincodeLabel)
                            .addComponent(pincodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(saveButton)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        Community newPerson = new Community();
        try {

            newPerson.setLocation(locationField.getText());
            newPerson.setDistrict(districtField.getText());
            newPerson.setCity(cityField.getText());
            newPerson.setProvince(provinceField.getText());
            newPerson.setPincode(pincodeField.getText());

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this,"please enter correct details");

        }

        persons.addPerson(newPerson);
        System.out.println(persons);
        JOptionPane.showMessageDialog(this,"User saved successfully");
         populateTable();

    }//GEN-LAST:event_saveButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = userTable.getSelectedRow();
        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to be viewed", "Error - No selection", JOptionPane.WARNING_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) userTable.getModel();
            Community selectedPerson = (Community) model.getValueAt(selectedIndex, 0);
            locationField.setText(selectedPerson.getLocation());
            districtField.setText(selectedPerson.getDistrict());
            cityField.setText(selectedPerson.getCity());
            provinceField.setText(selectedPerson.getProvince());
            pincodeField.setText(selectedPerson.getPincode());

        }
    }//GEN-LAST:event_viewButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = userTable.getSelectedRow();
        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to be deleted", "Error - No selection", JOptionPane.WARNING_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) userTable.getModel();
            Community selectedPerson = (Community) model.getValueAt(selectedIndex, 0);
            persons.removePerson(selectedPerson);
            JOptionPane.showMessageDialog(this, "Employee Information is deleted successfully.");
            populateTable();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void locationField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationField1ActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        Community selectedPerson;
        int selectedIndex = userTable.getSelectedRow();
        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to be updated", "Error - No selection", JOptionPane.WARNING_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) userTable.getModel();
            selectedPerson = (Community) model.getValueAt(selectedIndex, 0);
            selectedPerson.setLocation(locationField1.getText());
            selectedPerson.setDistrict(districtField1.getText());
            selectedPerson.setCity(cityField1.getText());
            selectedPerson.setProvince(provinceField1.getText());
            selectedPerson.setPincode(pincodeField1.getText());
            JOptionPane.showMessageDialog(this, "User updated successfully", "Success", HEIGHT);
            populateTable();
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void locationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationFieldActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void patient1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patient1ButtonActionPerformed
        // TODO add your handling code here:
        patientFrame1 patientFrame1 = new patientFrame1(bottomPanel, patients);
        bottomPanel.add("PatientFrame", patientFrame1);
        CardLayout layout =(CardLayout)bottomPanel.getLayout();
        layout.next(bottomPanel);
    }//GEN-LAST:event_patient1ButtonActionPerformed

    private void doctor1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctor1ButtonActionPerformed
        Doctor1Screen formPanel = new Doctor1Screen(bottomPanel, doctors);
        bottomPanel.add("CreateScreen", formPanel);
        CardLayout layout =(CardLayout)bottomPanel.getLayout();
        layout.next(bottomPanel);
        // TODO add your handling code here:
    }//GEN-LAST:event_doctor1ButtonActionPerformed

    private void communityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityButtonActionPerformed
        // TODO add your handling code here:
        adminFrame formPanel = new adminFrame(bottomPanel, persons);
        bottomPanel.add("CreateScreen", formPanel);
        CardLayout layout =(CardLayout)bottomPanel.getLayout();
        layout.next(bottomPanel);
    }//GEN-LAST:event_communityButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addCommunityDetailsLabel;
    private javax.swing.JLabel adminViewLabel;
    private javax.swing.JTextField cityField;
    private javax.swing.JTextField cityField1;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel cityLabel1;
    private javax.swing.JButton communityButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField districtField;
    private javax.swing.JTextField districtField1;
    private javax.swing.JLabel districtLabel;
    private javax.swing.JLabel districtLabel1;
    private javax.swing.JButton doctor1Button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField locationField;
    private javax.swing.JTextField locationField1;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel locationLabel1;
    private javax.swing.JButton patient1Button;
    private javax.swing.JTextField pincodeField;
    private javax.swing.JTextField pincodeField1;
    private javax.swing.JLabel pincodeLabel;
    private javax.swing.JLabel pincodeLabel1;
    private javax.swing.JTextField provinceField;
    private javax.swing.JTextField provinceField1;
    private javax.swing.JLabel provinceLabel;
    private javax.swing.JLabel provinceLabel1;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JTable userTable;
    private javax.swing.JButton viewButton;
    private javax.swing.JLabel viewCommunityDetailsLabel;
    // End of variables declaration//GEN-END:variables

 public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
        model.setRowCount(0);
        
        for(Community u: persons.getAllUsers()){
            Object[] row= new Object[5]; 
            
            row[0] = u;
//            row[0] = u.getLocation();
            row[1] = u.getDistrict();
            row[2] = u.getCity();
            row[3] = u.getProvince();
            row[4] = u.getPincode();
            model.addRow(row);
        }
        clearFields();
    }

    public void clearFields() {
        
        locationField1.setText("");
        districtField1.setText("");
        cityField1.setText("");
        provinceField1.setText("");
        pincodeField1.setText("");
        
    }

}
