/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package doctor_view;

import Model.BloodDonar;
import Model.DoctorDirectory;
import Model.PatientDirectory;
import Model.Person;
import admin_View.adminFrame;
import blood_view.Blood1Screen;
import java.awt.CardLayout;
import patient_View.patientFrame1;

/**
 *
 * @author jeyarajjeyakumar
 */
public class FirstScreen extends javax.swing.JFrame {

    /**
     * Creates new form FirstScreen
     */
    PatientDirectory patients;
    DoctorDirectory doctors;
    Person persons;
    public FirstScreen() {
        initComponents();
        doctors=new DoctorDirectory();
        persons=new Person();
        patients=new PatientDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        topPanel = new javax.swing.JPanel();
        patientButton = new javax.swing.JButton();
        doctorButton = new javax.swing.JButton();
        adminButton = new javax.swing.JButton();
        hospitalApplication = new javax.swing.JLabel();
        bloodButton = new javax.swing.JButton();
        vaccinationButton = new javax.swing.JButton();
        ambulanceButton = new javax.swing.JButton();
        bottomPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        patientButton.setText("Patient");
        patientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientButtonActionPerformed(evt);
            }
        });

        doctorButton.setText("Doctor");
        doctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorButtonActionPerformed(evt);
            }
        });

        adminButton.setText("Admin");
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        hospitalApplication.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        hospitalApplication.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalApplication.setText("Hospital Application");

        bloodButton.setText("Blood Donar");
        bloodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodButtonActionPerformed(evt);
            }
        });

        vaccinationButton.setText("vaccination");
        vaccinationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccinationButtonActionPerformed(evt);
            }
        });

        ambulanceButton.setText("Ambulance");
        ambulanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambulanceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addComponent(hospitalApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(patientButton)
                .addGap(39, 39, 39)
                .addComponent(doctorButton)
                .addGap(32, 32, 32)
                .addComponent(adminButton)
                .addGap(18, 18, 18)
                .addComponent(bloodButton)
                .addGap(18, 18, 18)
                .addComponent(vaccinationButton)
                .addGap(18, 18, 18)
                .addComponent(ambulanceButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addComponent(hospitalApplication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientButton)
                    .addComponent(doctorButton)
                    .addComponent(adminButton)
                    .addComponent(bloodButton)
                    .addComponent(vaccinationButton)
                    .addComponent(ambulanceButton))
                .addGap(165, 165, 165))
        );

        jSplitPane1.setTopComponent(topPanel);

        bottomPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(bottomPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorButtonActionPerformed
        // TODO add your handling code here:
        Doctor1Screen formPanel = new Doctor1Screen(bottomPanel, doctors);
        bottomPanel.add("CreateScreen", formPanel);
        CardLayout layout =(CardLayout)bottomPanel.getLayout();
        layout.next(bottomPanel);
    }//GEN-LAST:event_doctorButtonActionPerformed

    private void patientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientButtonActionPerformed
        // TODO add your handling code here:
        patientFrame1 patientFrame1 = new patientFrame1(bottomPanel, patients);
        bottomPanel.add("PatientFrame", patientFrame1);
        CardLayout layout =(CardLayout)bottomPanel.getLayout();
        layout.next(bottomPanel);
    }//GEN-LAST:event_patientButtonActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
       
        // TODO add your handling code here:
        adminFrame adminFrame = new adminFrame(bottomPanel, persons);
        bottomPanel.add("AdminFrame", adminFrame);
        CardLayout layout =(CardLayout)bottomPanel.getLayout();
        layout.next(bottomPanel);
    }//GEN-LAST:event_adminButtonActionPerformed

    private void bloodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodButtonActionPerformed
       
        // TODO add your handling code here:
        Blood1Screen Blood1Screen = new Blood1Screen(bottomPanel, persons);
        bottomPanel.add("Blood1Screen", Blood1Screen);
        CardLayout layout =(CardLayout)bottomPanel.getLayout();
        layout.next(bottomPanel);
    }//GEN-LAST:event_bloodButtonActionPerformed

    private void vaccinationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccinationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccinationButtonActionPerformed

    private void ambulanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambulanceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ambulanceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JButton ambulanceButton;
    private javax.swing.JButton bloodButton;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton doctorButton;
    private javax.swing.JLabel hospitalApplication;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton patientButton;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton vaccinationButton;
    // End of variables declaration//GEN-END:variables

   


}
